### ISSUE TITLE
url in article MOSTO: A toolkit to facilitate security auditing of ICS devices using Modbus/TCP is not found

### ISSUE THREAD

**Issue by Ice-or-Fire** [reverseame/mosto-modbus-simulator#2]
Thanks for your inspiring job! But the url in the article MOSTO: A toolkit to facilitate security auditing of ICS devices using Modbus/TCP is https://github.com/ reverseame/MOSTO-pentesting-Modbus, but I can't find it, is it wrong?

**Comment by ricardojrdez** [comment]
Hi @Ice-or-Fire, the URL in the paper is wrong, you're correct. It should be "https://github.com/reverseame/MOSTO-Modbus-simulator" (I've slightly renamed the repository). Thanks for pointing it out!
